### ISSUE TITLE
chore: pull acvm_js into acvm

### ISSUE THREAD

**Issue by kobyhallx** [noir-lang/acvm#458] opened 2023-07-26 17:06 UTC
### Problem

Current workflow with acvm_js is less convenient.

### Happy Case

acvm_js existing as workspace item in acvm

### Alternatives Considered

None

### Additional Context

In attempt to simplify dev workflow and release process we are pulling as much repositories together.

### Would you like to submit a PR for this Issue?

Yes

**Comment by TomAFrench** [comment] 2023-08-02 17:37
Dupe of #465

**Closed by TomAFrench** 2023-08-02 17:37 UTC
Labels: enhancement
